apiVersion: skaffold/v1
kind: Config
metadata:
  name: informer
build:
  artifacts:
  - image: wdalmut/informer
    context: src/informer
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/namespace.yaml
    - k8s/*
